(function () {
  var vscode = acquireVsCodeApi();

  var GH_SVG = '<svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"/></svg>';

  function show(id) {
    var views = document.querySelectorAll('.view');
    for (var i = 0; i < views.length; i++) { views[i].classList.remove('active'); }
    document.getElementById(id).classList.add('active');
  }

  function esc(s) {
    return String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }

  function liItems(arr) {
    return arr.map(function (x) { return '<li>' + esc(x) + '</li>'; }).join('');
  }

  function resetLoginBtn() {
    var lb = document.getElementById('loginBtn');
    if (!lb) { return; }
    lb.disabled = false;
    lb.innerHTML = GH_SVG + ' Continuar con GitHub';
  }

  // ── Button listeners ──────────────────────────────────────────────────────

  document.getElementById('loginBtn').addEventListener('click', function () {
    this.disabled = true;
    this.textContent = 'Conectando...';
    document.getElementById('loginErr').innerHTML = '';
    vscode.postMessage({ command: 'login' });
  });

  document.getElementById('logoutBtn').addEventListener('click', function () {
    vscode.postMessage({ command: 'logout' });
  });

  document.getElementById('backBtn').addEventListener('click', function () {
    show('vModules');
    vscode.postMessage({ command: 'loadModules' });
  });

  document.getElementById('validateBtn').addEventListener('click', function () {
    this.disabled = true;
    this.textContent = 'Evaluando...';
    document.getElementById('resultArea').innerHTML = '';
    vscode.postMessage({ command: 'validate' });
  });

  // ── Global helpers for inline onclick generated by renderModules ──────────

  window.toggleMod = function (el) { el.classList.toggle('open'); };
  window.startEx = function (slug) {
    show('vLoading');
    document.getElementById('loadTxt').textContent = 'Preparando misión...';
    vscode.postMessage({ command: 'startExercise', slug: slug });
  };

  // ── Renderers ─────────────────────────────────────────────────────────────

  function renderModules(data, username) {
    var totalEx = 0, doneEx = 0;
    for (var i = 0; i < data.length; i++) { totalEx += data[i].totalExercises; doneEx += data[i].completedExercises; }
    var pct = totalEx > 0 ? Math.round(doneEx / totalEx * 100) : 0;
    var initial = username ? username[0].toUpperCase() : '?';

    var html = '<div class="user-badge">'
      + '<div class="avatar">' + esc(initial) + '</div>'
      + '<div><div class="user-name">@' + esc(username || 'explorador') + '</div>'
      + '<div class="user-stats">' + doneEx + '/' + totalEx + ' misiones completadas</div></div>'
      + '</div>'
      + '<div class="global-prog">'
      + '<div class="prog-label"><span>Progreso total</span><span>' + pct + '%</span></div>'
      + '<div class="track"><div class="fill" style="width:' + pct + '%"></div></div>'
      + '</div>';

    for (var m = 0; m < data.length; m++) {
      var mod = data[m];
      var mpct = mod.totalExercises > 0 ? Math.round(mod.completedExercises / mod.totalExercises * 100) : 0;
      html += '<div class="mod-card">'
        + '<div class="mod-header" onclick="toggleMod(this.parentElement)">'
        + '<span class="mod-icon">' + esc(mod.icon) + '</span>'
        + '<div class="mod-meta"><div class="mod-title">' + esc(mod.title) + '</div>'
        + '<div class="mod-count">' + mod.completedExercises + '/' + mod.totalExercises + ' misiones</div></div>'
        + '<div class="mini"><div class="track"><div class="fill" style="width:' + mpct + '%"></div></div></div>'
        + '<span class="chevron">&#x25BC;</span>'
        + '</div><div class="ex-list">';

      var exs = mod.exercises || [];
      for (var e = 0; e < exs.length; e++) {
        var ex = exs[e];
        var num = ex.completed ? '<div class="ex-num done">&#x2713;</div>' : '<div class="ex-num">' + (e + 1) + '</div>';
        var btn = ex.completed
          ? '<button class="btn-start btn-retry" onclick="startEx(\'' + esc(ex.slug) + '\')">Rehacer</button>'
          : '<button class="btn-start" onclick="startEx(\'' + esc(ex.slug) + '\')">Iniciar</button>';
        html += '<div class="ex-row">' + num
          + '<div class="ex-info"><div class="ex-title" title="' + esc(ex.title) + '">' + esc(ex.title) + '</div></div>'
          + '<span class="tag tag-' + ex.type + '">' + ex.type.toUpperCase() + '</span>' + btn + '</div>';
      }
      html += '</div></div>';
    }
    document.getElementById('modList').innerHTML = html;
  }

  function renderExercise(ex) {
    document.getElementById('exTitle').textContent = ex.title;
    document.getElementById('exDesc').textContent = ex.description || '';
    var pill = document.getElementById('exTypePill');
    var labels = { html: 'HTML/CSS', js: 'JavaScript', terminal: 'Terminal' };
    var pillCls = { html: 'tag-html', js: 'tag-js', terminal: 'tag-terminal' };
    pill.textContent = labels[ex.type] || ex.type;
    pill.className = 'tag ' + (pillCls[ex.type] || '');
    var instrs = {
      html: '<strong>Edita</strong> index.html y style.css que se abrieron. Cuando termines, valida.',
      js: '<strong>Edita</strong> mision.js. Prueba con <strong>node mision.js</strong> en la terminal. Luego valida.',
      terminal: 'Sigue las instrucciones en <strong>respuestas.md</strong>. Ejecuta los comandos en la terminal. Pega los outputs y valida.'
    };
    document.getElementById('exInstr').innerHTML = instrs[ex.type] || '';
    document.getElementById('resultArea').innerHTML = '';
    var vBtn = document.getElementById('validateBtn');
    vBtn.disabled = false;
    vBtn.textContent = '\uD83D\uDEF8 Validar Misión';
    show('vExercise');
  }

  function renderResult(r) {
    var vBtn = document.getElementById('validateBtn');
    vBtn.disabled = false;
    vBtn.textContent = '\uD83D\uDEF8 Validar Misión';
    var pass = r.aprobado;
    var html = '<div class="result-box ' + (pass ? 'pass' : 'fail') + '">'
      + '<div class="result-hdr"><span class="result-icon">' + (pass ? '🏆' : '🔴') + '</span>'
      + '<span class="result-ttl ' + (pass ? 'pass' : 'fail') + '">' + (pass ? '¡Misión completada!' : 'Misión incompleta') + '</span></div>'
      + '<div class="result-msg">' + esc(r.mensajeGeneral) + '</div>';
    if (r.cosasBuenas && r.cosasBuenas.length) { html += '<div class="rs good"><h4>Lo que hiciste bien</h4><ul>' + liItems(r.cosasBuenas) + '</ul></div>'; }
    if (r.cosasMalas && r.cosasMalas.length) { html += '<div class="rs bad"><h4>Errores a corregir</h4><ul>' + liItems(r.cosasMalas) + '</ul></div>'; }
    if (r.revisar && r.revisar.length) { html += '<div class="rs tip"><h4>Para mejorar</h4><ul>' + liItems(r.revisar) + '</ul></div>'; }
    html += '</div>';
    document.getElementById('resultArea').innerHTML = html;
  }

  // ── Message listener ──────────────────────────────────────────────────────

  window.addEventListener('message', function (e) {
    var msg = e.data;
    switch (msg.command) {
      case 'loading':
        document.getElementById('loadTxt').textContent = msg.text || 'Cargando...';
        show('vLoading');
        break;
      case 'validating':
        document.getElementById('validateBtn').disabled = true;
        document.getElementById('validateBtn').textContent = 'Evaluando con IA...';
        break;
      case 'modulesLoaded':
        renderModules(msg.modules, msg.username);
        show('vModules');
        break;
      case 'loggedOut':
      case 'loginCancelled':
        show('vLogin');
        resetLoginBtn();
        break;
      case 'exerciseStarted':
        renderExercise(msg.exercise);
        break;
      case 'validationResult':
        renderResult(msg.result);
        break;
      case 'error': {
        resetLoginBtn();
        var ae = document.querySelector('.view.active');
        if (ae) {
          var eb = ae.querySelector('.err-box');
          if (!eb) { eb = document.createElement('div'); eb.className = 'err-box'; ae.appendChild(eb); }
          eb.textContent = msg.text;
        }
        break;
      }
    }
  });
})();
